issuer: https://accounts.google.com

# staging-images: not in use
# prod-images: insights-publisher-sa@prod-images-c6e5.iam.gserviceaccount.com
subject: "101826719708554282120"

permissions:
  contents: write
  issues: write
  pull_requests: write
  workflows: write

repositories:
  - os
